name: Lint
on:
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/tsuyoshicho/action-textlint
      - uses: tsuyoshicho/action-textlint@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          level: warning
          reporter: github-pr-review
          textlint_flags: 'articles/**'
  security_check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - uses: actions/checkout@v4
      # https://github.com/aquasecurity/trivy-action
      - uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-ref: package-lock.json
          scan-type: fs
          trivy-config: .trivy.yaml
